apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: otel-collector
  namespace: monitoring

spec:
  namespaceSelector:
    matchNames:
      - observability

  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector-collector

  endpoints:
    - port: prometheus
      interval: 15s
      path: /metrics