apiVersion: monitoring.coreos.com/v1
kind: Probe

metadata:
  name: flask-probe
  namespace: monitoring

  labels:
    release: prometheus

spec:

  jobName: flask-blackbox

  interval: 30s

  module: http_2xx

  prober:
    url: blackbox-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115

  targets:

    staticConfig:

      static:

      - http://flask.flask.svc.cluster.local