apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aleemahmad0508/flask-helm-chart.git
    targetRevision: main
    path: observability

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
