apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:

  name: prometheus

  namespace: argocd


spec:

  project: default


  destination:

    server: https://kubernetes.default.svc

    namespace: monitoring


  source:

    chart: kube-prometheus-stack

    repoURL: https://prometheus-community.github.io/helm-charts

    targetRevision: 87.19.0


   

  helm:

    values: |

      alertmanager:

          enabled: true


          config:

            global:

              resolve_timeout: 5m


            route:

              group_by:
                - alertname

              group_wait: 30s

              group_interval: 5m

              repeat_interval: 1h

              receiver: slack


            receivers:


            - name: slack


              slack_configs:


              - api_url: slack-webhook

                channel: "#flask-alerts"

                send_resolved: true

          configSecret: alertmanager-slack-config


  syncPolicy:

    automated:

      prune: true

      selfHeal: true


    syncOptions:

    - CreateNamespace=true
